basePath: /
definitions:
  models.Book:
    properties:
      author:
        type: string
      id:
        type: integer
      name:
        type: string
      publication:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Swagger API Team
    url: http://swagger.io/support
  description: This is a sample bookstore API
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: The Bookstore API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: get all saved books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
        "404":
          description: No books found
          schema:
            type: string
      summary: Get books
    post:
      consumes:
      - application/json
      description: create book
      parameters:
      - description: Book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Book'
        "400":
          description: Bad request
          schema:
            type: string
      summary: Create book
  /books/{id}:
    delete:
      consumes:
      - application/json
      description: delete book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete book
    get:
      consumes:
      - application/json
      description: get book by id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "404":
          description: Book with id not found
          schema:
            type: string
      summary: Get book by id
    put:
      consumes:
      - application/json
      description: update book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      - description: Book
        in: body
        name: book
        required: true
        schema:
          $ref: '#/definitions/models.Book'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Book with id not found
          schema:
            type: string
      summary: Update book
swagger: "2.0"
